description = ""
distro = ""
groups = []
modules = []
name = "webserver"
version = "0.0.5"

[customizations]
  hostname = "mywebserver.io"

  [[customizations.user]]
    description = "webmaster"
    groups = ["wheel"]
    key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD1+wnJsV3ua2c3KITsyT4fYRxX3WiET/w0SDP/juFlmWQvwKnWpEniDTknitEfEcO217rDkkHBqdTP69aKxwYbqrXeTZnvgbhpcs5bPwGMQmU/xm966oSGNHnLS1WuILAXwtu/0JtwPLCcfHqjV8oIOaujfooSVTU2NutPwolsnB5izHRKr5HYOM5hZf6V2Z7DOYEqzOp/zrniLLoDHS3l9HT93Oh8BaLfwsCsG8xBBsCCOMaJQEAlBNYUgZ/gGLP619bZYWkxtk6nq0M59VET+R6NtiDR2oCDKLoAP+gJv5PCOeAux4rezJp74kr+EWh3yrkgLaoprc05/vvpa5g2yvV3+iX+FSEr2mEzga6PNGTvpVXNnCTMg7ofvNmaOov3chU0LsoNpFcbX2ncgjUesYKtS1/sm7dYNVX0rf7ZRNDkLg09QdRhpM+26Z5+v4N1QbmGOAHQ5znpT2FPl1xQEvW8QwwSj2qkVVcdVhglxuoQh17jRbvYbZlwzLbRvgcwpZDiibgowAaMzPUViSwd/YyCsrrZEn9/bHW8AZAfzjjSoOZDI/UknmeATG9B3qVyFC6Fgx7I1rXzdzj6l0+Kn5Byssvvd+VDoO4i6T0Gu4GT6oPRmz63nbPu5m2fTfldwMOYPLZRlQ5bTkWrV7p8fTHJAidlYZCNpJUlMFE0JQ== me@demo"
    name = "webmaster"
    password = "$6$L.2vP6DpSAKifcXg$fM1EQtUYy09ehWqyoESMPhBSwmu2tcAW/heMue9Sd5WarKomHDoT4EvhfX729Iyji116xwk2KMX4qkNvA9ZYP."

  [customizations.firewall.services]
    enabled = ["ssh", "http", "https"]

  [customizations.services]
    enabled = ["sshd", "httpd"]

[[packages]]
  name = "httpd"
  version = "*"

[[packages]]
  name = "mod_ssl"
  version = "*"

[[packages]]
  name = "firewalld"

[[packages]]
  name = "gobject-introspection"
  version = "*"
