= Using Buildah

Whilst we do have a cockpit extension for managing containers via Podman, we'll be
interacting with link:https://buildah.io/[Buildah] on the command line.

We're going to use the RHEL UBI minimal images to build these demo containers
as these are freely redistributable base container images that are well maintained
by Red Hat. 

== Simple webserver container

On our build VM we will create a very simple 
link:../buildah/ubi-minimal-httpd/Dockerfile[webserver image] with a dummy
link:../buildah/ubi-minimal-httpd/index.html[index.html]


[source,bash]
----
cd /opt/ephemeral-world/buildah
cd ubi-minimal-httpd
buildah build-using-dockerfile -t ubi-minimal-httpd .

buildah images
----

Then to test the image we'll use podman

[source,bash]
----

podman run -d -p 8000:80 --name simple-httpd localhost/ubi-minimal-httpd

curl http://localhost:8000/
----

You can also look at the container via

[source,bash]
----

podman ps
podman logs -f simple-httpd

# and stop the container
podman stop simple-httpd
podman rm simple-httpd

# and if we want we can clean up the built image
podman rmi simple-httpd
----

== Scripted vs Dockerfile

Here is an alternative approach (link:../buildah/ubi-minimal-httpd.sh[ubi-minimal-httpd.sh])
where we script the build directly with buildah

This interacts directly with the container and then saves the final image.

[source,bash]
----
cd /opt/ephemeral-world/buildah
cat ubi-minimal-httpd.sh

./ubi-minimal-httpd.sh

buildah images
----

We can test this again using podman
[source,bash]
----

podman run -d -p 8000:80 --name simple-httpd localhost/ubi-minimal-scripted-httpd

curl http://localhost:8000/
----

Once finished we can stop and clean up the container

[source,bash]
----
podman stop simple-httpd
podman rm simple-httpd
----

== Red Hat Provided Apache Image

We could also leverage the offical link:https://catalog.redhat.com/software/containers/rhel8/httpd-24/5ba0addbbed8bd6ee819856a?container-tabs=overview[Red Hat maintained pre-build Apache 2.4 image]


[source,bash]
----
podman login registry.redhat.io
Username: {REGISTRY-SERVICE-ACCOUNT-USERNAME}
Password: {REGISTRY-SERVICE-ACCOUNT-PASSWORD}


buildah pull registry.redhat.io/rhel8/httpd-24
----

== Bugs / Issues

You need to be careful of your RPM versions if you're going to work with ubi-micro images.
These images build outside of the container and your host needs to support the RPM database
technology for the target image. For example you can't build a RHEL8 ubi-micro image on
Fedora 35 as it used a newer RPM DB format

---
link:ImageBuilder.adoc[Go back to Image Builder] or
link:../README.adoc[Return]
